API changes for molecular Consequences
FHIR/genomics-operations pull request #70
Opened 2023-08-28 16:48 UTC by Arraxx

## Description

Added API changes for molecular Consequences and added find-subject-molecular-consequences in herokuapp.

2023-09-05 17:48 UTC, Arraxx commented
please review @mihaitodor @rhdolin

2023-09-06 14:20 UTC, mihaitodor requested changes
Thanks Aman! I had a quick look and pointed out some potential issues.

Please also add some automated tests to https://github.com/FHIR/genomics-operations/tree/main/tests/integration_tests similar to the other operations.

2023-09-06 14:20 UTC, mihaitodor commented on app/common.py
> +    pipeline_part = [{'$match': {'$expr': {'$and': [{'$or': [{'$eq': ['$variantID', '$$myvariant_id']}]}]}}},
What is `$$myvariant_id`?

2023-09-06 14:20 UTC, mihaitodor commented on app/common.py
> +        print(f"{e}")
Please use the same `print()` pattern that's already used throughout this file (smth like `print(f"DEBUG: Error{e} under query_molecular_consequences_by_variants query={query}")`)

2023-09-06 14:20 UTC, mihaitodor commented on app/common.py
> +        item["UUID"] = str(uuid4())
Why generate a new random UUID?

2023-09-06 14:20 UTC, mihaitodor commented on app/endpoints.py
> +                    # resource = common.create_fhir_variant_resource(
Please remove commented-out code or add some comment to explain why it exists (same for line 1280)

2023-09-27 16:19 UTC, Arraxx commented on app/common.py
> +        item["UUID"] = str(uuid4())
Variant id should be unique.

2023-10-19 14:38 UTC, mihaitodor commented on app/common.py
> +    pipeline_part = [{'$match': {'$expr': {'$and': [{'$or': [{'$eq': ['$variantID', '$$myvariant_id']}]}]}}},
Oh, OK. I see. It's following an existing pattern (see `$$mygenotypeCode`).

2024-05-11 17:58 UTC, rhdolin commented
this change is part of a new pull request

2024-05-11 17:58 UTC, closed without merging